services:
  localstack:
    image: localstack/localstack
    container_name: localstack_main
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack gw
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - PERSISTENCE=1
    volumes:
      - "./localstack_data:/var/lib/localstack" 
      - "/var/run/docker.sock:/var/run/docker.sock"
